print("Everyone loves baseball! Go blue jays!")
print("Welcome to the slugging percentage calculator!")
name = raw_input("Enter the player's name: ")
singles = float(input("Enter the number of singles " + name + " has hit: "))
doubles = float(input("Enter the number of doubles " + name + " has hit: "))
triples = float(input("Enter the number of triples " + name + " has hit: "))
homers = float(input("Enter the number of home runs " + name + " has hit: "))
ab = float(input("Enter the number of at bats " + name + " has had: "))
slug = float((singles + (2*doubles) + (3*triples) + (4*homers))/ab)
print (name + "'s slugging percentage is " + str(slug))